### ISSUE TITLE
dependencies are out of date

### ISSUE THREAD

**Issue by diracdeltas** [uphold/http-request-signature#8]
for instance, https://github.com/uphold/http-request-signature/blob/master/yarn.lock pins tweetnacl to 0.14.x. We would like to use this but are not sure if it's still being maintained.

**Comment by waldyrious** [comment]
Hi @diracdeltas, thanks for your interest in this project. It's not really abandoned -- it's one of many packages we're using, and we simply haven't had the need for new development work in this particular repo for a while, so it wasn't a priority for us to upgrade the dependencies. (Note that doing so could require thorough testing to ensure no regressions are introduced, due to the cross-links in the dependency tree.)

With that in mind, we'd encourage you to use the project, and we'd appreciate reports of any issues you might encounter, or even better, PRs to address them. We can't promise a specific timeline to address them, but we will make sure to get to them as soon as possible.

By the way, note that (1) tweetnacl is only used by jest, which is a development dependency, i.e., it won't affect downstream projects, so such cases may hopefully not be an issue for you; and (2) our `package.json` does not pin dependencies, precisely so that downstream projects can use later versions than those that currently appear in `yarn.lock`. Hope that helps!

**Comment by diracdeltas** [comment]
@waldyrious thanks for the response. in case it wasn't clear, I run security at Brave Software, one of Uphold's partners (i think the one that originally requested this repo for our Uphold integration). We would like you guys to keep the deps up to date since we still use it for stuff. Alternatively we could fork it and then maintain it ourselves.

**Comment by diracdeltas** [comment]
@nunofgs is it used here as a non-dev dependency? https://github.com/uphold/http-request-signature/blob/master/src/verify.js

the context here is @amirsaber is trying to use this package for signing/verifying HTTP headers. He tried using your package with Tweetnacl 1.0 instead of 0.14.3 but faced compatibility issues with this function: https://github.com/uphold/http-request-signature/blob/master/src/sign.js#L26

> With Tweetnacl 1.0 The problem is with secretKey, If I send secret key as a hex string, Tweetnacl library will throw unexpected type, use Uint8Array and if I send it as a Uint8Array the validate function will throw ValidationFailedError: 400 Validation Failed since it's not matching const ED25519_SECRET_KEY = /^[A-Fa-f0-9]{128}$/; regex.

**Comment by nunofgs** [comment]
> @nunofgs is it used here as a non-dev dependency? https://github.com/uphold/http-request-signature/blob/master/src/verify.js#L9

Ah, you're absolutely correct. Looks like we neglected to add it as an explicit dependency in `package.json`.

> the context here is @amirsaber is trying to use this package for signing/verifying HTTP headers. He tried using your package with Tweetnacl 1.0 instead of 0.14.3 but faced compatibility issues

I was trying to figure out why you'd be bumping Tweetnacl on your end instead of relying on the dependency tree but, of course, the reason is that we hadn't listed it as a dependency.

We'll take care of updating this asap.
